### ISSUE TITLE
Implement final agreement and claim confirmation

### ISSUE THREAD

**Issue by LLL263** [CS778-S2-2026-AWS-Challenge/scenario-08-northwind-fnol-agent#928]
### Issue type

Feature

### Problem or reason

**Flow:** AI collection → Review information (#924) → Payout & contact (#926) → **Agreement & submit (this issue)**.

Before a Claim is formally submitted, the claimant needs a final confirmation step where they understand what they are submitting and explicitly confirm the required declaration or agreement.

The system must not treat information collected by the AI as a final submission without clear claimant confirmation.

### Deliverable

Implement **Step 4 – Agreement & confirmation** on the claimant side as the final step before the Claim is formally submitted.

**Expected user flow**

1. Customer completes the information review.
2. Customer completes payout and contact preferences.
3. Customer enters the final confirmation page.
4. Customer reviews the final submission summary.
5. Customer reads the required declaration or agreement.
6. Customer explicitly confirms the required items.
7. Customer selects **Submit claim**.
8. The Claim is submitted through the existing contract.
9. Customer sees a clear submission-success state and Claim reference where supplied by that contract.

**Page structure**

1. **Final summary** – Show a concise summary such as Claim type, incident date, insured item/property, claimant, evidence received, preferred contact method, and payout-details status. Do not repeat the entire Step 2 page. Provide a **Review information** action so the customer can return and make corrections.
2. **Agreement / declaration** – Display only approved declaration, consent, privacy, or submission text supplied by the applicable product/legal/business contract. **Do not invent legal wording in the frontend.** Where explicit confirmation is required, use clear controls whose wording and requiredness follow the approved contract.
3. **Final submit action** – Provide one clear primary action labelled **Submit claim**. Keep it unavailable until all required confirmations are complete, and make clear that it formally submits the Claim.

**Submission behaviour**

When the claimant selects **Submit claim**:

- validate that required previous steps are complete;
- validate required agreements;
- submit through the existing Claim submission API/action;
- prevent accidental duplicate submissions;
- show a loading/submitting state while the request is in progress;
- handle failure without losing the customer's entered information.

After successful submission:

- show a confirmation state;
- show the Claim/reference number when returned by the contract;
- explain the defined next step;
- show the preferred contact method where useful;
- provide a clear route back to the Claim, conversation, or dashboard.

**Contract gaps / implementation notes**

- Approved agreement text, required confirmation fields, versioning/audit requirements, submission preconditions, target Claim state, idempotency behavior, and the success payload must come from existing product/legal/backend contracts.
- If any of these contracts are absent or incomplete, **do not invent legal wording, backend fields, transitions, or success data in the frontend**. Record the specific gap and keep formal submission unavailable until it is resolved.
- Example legal confirmation language is intentionally omitted until approved copy exists.

### Acceptance criteria

- [ ] The claimant can see a concise final summary before submission.
- [ ] The claimant can return to the review step if they notice incorrect information.
- [ ] Required approved agreement/declaration content is visible before submission.
- [ ] Required confirmations are explicit rather than assumed.
- [ ] The Claim cannot be submitted until required confirmations are complete.
- [ ] The final action is clearly labelled as the Claim submission action.
- [ ] Duplicate submission is prevented while a submission is already in progress.
- [ ] Submission errors are communicated without losing Claim data.
- [ ] Successful submission changes the Claim into the appropriate state defined by the existing contract.
- [ ] The success screen shows the Claim reference and next step when supplied by the existing contract.
- [ ] No staff-only, risk, fraud, routing, or internal AI signals are exposed.
- [ ] Existing Claim history and conversation data remain available after submission.

### Related issue or PR

Refs #924 and #926.

### Dependencies

- #924 – Claim information review and confirmation.
- #926 – Payout details and contact preferences.
- Existing Claim Context.
- Existing Claim submission API/action contract.
- Approved declaration/agreement content and confirmation contract.
- Existing visibility rules.

### Owned behavior

The claimant-side Step 4 final summary, approved-agreement presentation, explicit confirmation gating, single-submit behavior, error preservation, and success state around the existing submission contract.

### Expected impact area

- Claimant/customer frontend final-confirmation and success surfaces.
- Existing Claim Context and claim-submission action integration.
- Existing agreement/consent copy source and any version/audit read-through.
- Submission idempotency/error handling and related tests.
- Relevant documentation only if an approved shared contract changes.

### Non-goals

- Do not write or decide legal policy.
- Do not invent agreement wording that has not been approved.
- Do not redesign the staff review process.
- Do not implement claim assessment or approval.
- Do not automatically approve or pay the Claim after submission.
- Do not redesign unrelated claimant pages.

### Shared contracts

- Claim submission preconditions, command/action, target state, idempotency, errors, and success payload.
- Approved declaration/agreement source, exact copy, version, required confirmations, and audit requirements.
- Claimant visibility rules and Claim summary projection.
- Step-completion state shared with #924 and #926.

Any missing contract is a recorded blocker; this issue does not invent legal text or backend capability.

### Risk class

External side effect

### Owner or responsible contributor

Unassigned — assign one responsible contributor before implementation begins.

**Comment by Ysoseri1224** [comment]
The issue policy check found:
- Issues created by contributors other than the maintainer require prior approval: post in the `Issue requests` Discussions category, wait for the maintainer's explicit approval reply, and record the thread URL in `### Discussion approval`.

Update this issue using the **Code work** form. This check does not close or delete issues.

**Comment by jxu316-arch** [comment]
Implementation blocker audit after PR #913 merged and Issue #924 work began:

1. **No approved agreement/declaration contract exists on current `main`.** Repository search found no claimant declaration/agreement resource, version, required-confirmation schema, approved legal copy source, or audit/version fields. This issue explicitly prohibits inventing that text or confirmation contract in the frontend, so the agreement section and its gating cannot be implemented authoritatively yet.

2. **The current claim-creation endpoint is the legacy direct-creation contract, not the new Step 4 submission contract.** `POST /api/v1/claims/{claim_id}/creation` checks Claim revision, registered CREATE_CLAIM requirements, open handoffs, and presence of a claimant message, then creates the external claim. It does not validate Step 3 payout/contact completion or an approved declaration/confirmation record. Current backend readiness therefore still projects `claimant.create_claim` immediately after Claim facts are ready.

3. **Issue #926 is a prerequisite and is currently contract-blocked.** Protected payment destinations are not implemented on current `main` (owned upstream by open Issue #923, dependent on open Issue #918), and the current `{email: bool, sms: bool}` communication-preferences contract does not define the preferred-contact method required by Issue #926.

4. **Existing idempotency/revision handling can be reused later but is not sufficient evidence for Step 4.** The legacy creation route already has `Idempotency-Key` and `If-Match` protections and a success payload with external Claim data. Those mechanisms are useful implementation primitives once the new submission preconditions/action contract exists, but calling this route now would bypass the new Step 3 + declaration requirements.

Formal Step 4 submission should therefore remain unavailable until the server-owned Step 3 completion contract and approved declaration/confirmation contract are published. No frontend-only legal text, completion flag, state transition, or success payload should be introduced.

**Comment by bdfa123** [comment]
## Current-main Step 4 blocker reconciliation — `main@861c15b`

**What.** The 17 September blocker audit above is now partly stale. Issues #918 and #923 are closed through PRs #944 and #971: current `main` has the protected Account `PaymentDestination` contract, claimant Profile contact destinations, and the registered Claim field `claimant.contact_preference`. PR #1004 now implements the separate Step 3 selection/progression slice for #926, but remains open and is not yet an authoritative `main` capability.

**Why.** The Step 4 blocker itself remains. A current-main contract/code search still finds no authoritative claimant declaration/agreement resource containing the approved copy, stable declaration identifier/version, required confirmations, claimant-visible projection, or durable acceptance/audit record. The hard-coded `guided-motor-prototype-v1` text in the historical Guided Motor prototype is explicitly prototype text and is not an approved shared contract. The existing `POST /api/v1/claims/{claim_id}/creation` route still provides useful revision, idempotency, external-Claim result, and success-payload primitives, but current `main` does not make Step 3 completion plus versioned declaration acceptance its formal submission preconditions. PR #1009, which advanced `main` to this head, hardens Evidence/Message integrity and does not supply this missing Step 4 contract.

Evidence level: **current-main API/domain/persistence contract audit**, not browser or completed-journey evidence.

**Who.** @jxu316-arch owns #928's claimant Step 4 experience. @liyang6620 owns the shared backend/API contract needed by that experience. The exact declaration wording/source still requires the applicable product/legal/business authority; neither the frontend nor this validation line should invent it.

**How.** The minimum authoritative boundary needed before Step 4 implementation can be accepted is:

1. a stable declaration identifier/version and approved exact copy source;
2. explicit required confirmation fields and a claimant-safe projection;
3. a durable acceptance record bound to claimant, Claim, Claim revision, declaration version and timestamp;
4. a backend-owned Step 4 action/mutation with revision, idempotency, audit and realtime behavior;
5. formal creation preconditions that require valid Step 3 completion and current declaration acceptance, plus the defined target state/error/success contract;
6. fail-closed behavior when the declaration changes, acceptance is stale, or #1004's payout/contact authority is no longer valid.

**Requested action.** Keep formal submission unavailable until PR #1004 is merged and the six-point declaration/submission boundary above is published on this issue, a linked Discussion, or current contract documentation. If approved wording/source is unavailable, record that explicitly as the remaining blocker rather than substituting prototype text. Once those inputs are authoritative, #928 can implement the claimant UI around them; the #771 journey-validation line will then rerun the real path on the resulting exact `main` head rather than taking over this implementation.

**Comment by jxu316-arch** [comment]
@liyang6620 I’m starting #928 (Step 4 – Agreement & confirmation). The claimant UI can be implemented on top of the current `claimant.review_agreement` projection and existing `/claims/{claim_id}/creation` endpoint, but completing #928 correctly appears to require a small backend shared-contract slice rather than frontend-only gating.

The bounded backend need I see is:
- an authoritative approved agreement/declaration contract for the claimant flow (exact source/copy, version, and required confirmation fields);
- persisted/auditable acceptance bound to the authenticated claimant, Claim, current revision, and agreement version;
- `claimant.create_claim` becoming available only after the required acceptance is valid;
- `/creation` re-checking the Step 3 + agreement preconditions so the API cannot bypass Step 4;
- preserving the existing creation idempotency/success contract rather than redesigning claim creation.

I will not invent legal wording or change unrelated backend behavior. Before I touch the backend-owned area, can you confirm whether you want to implement this contract yourself, or whether you’re happy for me to implement this bounded slice and send it through review?

**Comment by liyang6620** [comment]
## Backend-owner delegation for the bounded #928 backend slice

@jxu316-arch, I am explicitly authorising you to implement the minimum backend support required to complete Issue #928.

I am delegating this one bounded slice because you already hold the detailed Step 4 journey context and I do not have capacity to implement it without delaying the claimant flow. This is a one-time delegation for #928 only. It does not transfer general backend ownership or authorise adjacent backend work.

### Current baseline

Use current `main@2d6499a7fb22a1e3a872f32241f8cdfa78e2dcf5` as the factual baseline:

- PR #1004 / Issue #926 is merged and provides the server-owned Step 3 payout/contact selection, contact-authority guard, `agreement_required`, and `claimant.review_agreement` projection.
- PR #1013 / Issue #987 is merged and owns Claim-creation Evidence/provenance validation, durable provider reservation, idempotent replay, unknown outcome, settlement, and reconciliation.
- PR #1021 / Issue #1006 is still active and changes shared repository, Claim, Message, Runtime/Handoff replay, and persistence documentation paths. Do not begin overlapping shared-file edits from an older base. Fetch again and base #928 work on the resulting current main after #1021 is resolved/merged, or stop and report any unavoidable overlap.

### Exact authorised outcome

Implement only the minimum bridge from the existing `claimant.review_agreement` state to the existing Claim creation contract:

1. Expose one authoritative claimant-safe agreement/declaration definition containing a stable identifier, version, approved exact display copy, and explicit required confirmation fields.
2. Accept the claimant's explicit confirmations through the server-owned Step 4 submission boundary.
3. Persist auditable acceptance bound to the authenticated claimant, Claim, relevant Claim revision, agreement identifier/version, and timestamp.
4. Make final submission fail closed unless the current Step 3 payout/contact state remains valid and the required current agreement confirmations are valid.
5. Prevent a direct call to `/api/v1/claims/{claim_id}/creation` from bypassing Step 3 or agreement confirmation.
6. Expose `claimant.create_claim` only when the backend-owned preconditions are satisfied.
7. Preserve the existing `/creation` idempotency, response, external Claim result, provider reservation, failure classification, unknown-outcome recovery, and reconciliation behavior.
8. Let the claimant frontend consume the backend projection, submit once, retain data after failure, and show only the existing safe success result.

### Agreement-copy blocker

This delegation does **not** approve or supply legal/product wording.

- Do not use `guided-motor-prototype-v1` or its prototype text.
- Do not ask an AI to invent, paraphrase, or improve declaration, privacy, consent, or legal wording.
- Do not treat placeholder/example copy as approved.
- Before enabling formal submission, record the exact approved source, copy, identifier, version, and required confirmations in the #928 durable record and applicable current contract documentation.
- If that approved input is unavailable, implement no substitute. Keep formal submission unavailable and report the remaining blocker.

### Required minimal design constraints

Prefer reuse over new architecture:

- Reuse the existing Claim detail/action projection and existing `/creation` operation unless a proven contract conflict makes that impossible.
- Reuse existing Claim revision, idempotency, action/decision, audit, realtime, Fixture/Mongo parity, and #987 Claim-creation operation/recovery patterns.
- Add only the smallest agreement-specific model/record needed to prove the accepted agreement version and confirmations.
- Do not create a general legal-document platform, policy engine, configuration service, second submission lifecycle, background reconciliation system, or new external provider flow.
- Do not create a frontend-only acceptance flag or infer submission authority from local checkbox state.
- Do not encode agreement acceptance as an ordinary claimant Message.
- Do not hold the SQLite identity authority guard across a provider network call.
- Do not weaken, replace, or duplicate #1004's contact-authority guard or #987's provider-operation boundary.
- Do not add a new endpoint, persistence abstraction, or lifecycle state merely for stylistic preference. If an additional public endpoint or new shared abstraction is genuinely required, stop and explain why the existing boundary cannot carry #928 before implementing it.

For stale Claim revision, stale agreement version, missing confirmation, invalidated Step 3 state, or unavailable contact authority, fail before provider invocation with the existing bounded error-envelope conventions and with no false success projection. Exact idempotent replay must remain exact; changed input under the same key must conflict.

### Mandatory isolation from my backend-gap work

Do not implement, modify, refactor, anticipate, or partially solve:

- #984 ExternalTask attempt/outcome persistence;
- #985 Workbench staff least privilege;
- #1006 actor-scoped Message idempotency, anonymous Claim promotion, or Runtime/Handoff replay integrity;
- the completed #986 Evidence/Message validation and ordering contract;
- the completed #987 Claim-creation provider operation/recovery state machine;
- AWS migration, deployment, IaC, provider onboarding, or cloud validation.

In particular, do not change generic Message/Evidence validation, Runtime/Handoff result links, ExternalTask lifecycle, Workbench authority, staff permissions, anonymous promotion, or provider reconciliation as part of #928.

If #928 needs persistence changes in `backend/repositories/protocols.py`, `backend/repositories/fixture.py`, or `backend/repositories/mongodb.py`, keep them agreement-specific and additive, preserve all current-main methods and invariants, and re-check overlap after #1021. Do not resolve a semantic conflict by selecting an older branch version or by changing another Issue's tests. If the conflict is not purely mechanical, stop and report it before continuing.

### Scope and file discipline

The expected change area is limited to:

- an agreement-specific domain/contract model;
- claimant action/detail projection needed by Step 4;
- the existing Claim creation API/service precondition boundary;
- the minimum agreement acceptance persistence needed for Fixture/Mongo parity;
- the #928 claimant UI and API client;
- focused #928 tests and required API/persistence/OpenAPI documentation.

Do not edit unrelated Agent prompts, Message services, Evidence services, Runtime/Handoff services, ExternalTask services, Workbench services, staff authorization, AWS code, CI configuration, dependencies, fixtures unrelated to #928, or other journey pages.

Finding an adjacent defect does not authorise fixing it. Record it and leave it unchanged. Do not perform opportunistic cleanup, renaming, generalisation, formatting churn, or test refactoring outside the lines required by #928.

### Required evidence

Before requesting review, demonstrate at minimum:

- the backend projection returns the approved exact agreement ID/version/copy and required confirmations;
- missing or false required confirmation cannot submit;
- direct `/creation` access cannot bypass Step 3/agreement;
- stale Claim revision and stale agreement version fail before provider invocation;
- invalidated payout/contact authority fails before provider invocation;
- a valid submission invokes the existing Claim-creation boundary once and returns its existing success contract;
- retry with the same key replays without duplicate provider creation;
- changed input under the same key conflicts;
- provider failure/unknown outcome still follows #987 without losing the acceptance evidence or fabricating success;
- Fixture and MongoDB implement the same agreement-specific behavior;
- no staff-only, risk, fraud, routing, or internal Agent data enters the claimant projection;
- existing Claim history and conversation remain readable after submission.

Use deterministic unit/provider-parity tests. Do not describe mocks, fixtures, or configured adapters as real provider success.

### Delivery requirements

Before editing, fetch latest `origin/main`, read the complete current #928 record and affected contracts, and identify the exact approved agreement source. Before pushing, fetch again, inspect the complete diff against current main, and verify that no teammate or backend-gap change is overwritten.

Keep this as one coherent #928 branch/PR. Do not create or edit another Issue or Discussion, change Kanban/assignees/PR readiness, merge, or close #928 without explicit authorisation. Use `Refs #928` until the frontend, backend, approved copy, and complete acceptance evidence are all present; use `Closes #928` only if the PR genuinely satisfies every acceptance criterion.

All code, commits, tests, documentation, PR text, and review replies must be in English.

When requesting review, report the exact main SHA, exact head SHA, every changed file with its #928 reason, actual local commands/results, exact-head CircleCI, agreement-copy source/version, and remaining risks. Include this declaration:

> I confirm that this delivery is limited to Issue #928's Agreement & confirmation journey. It preserves #1004 and #987, and does not implement, modify, revert, anticipate, or weaken #984, #985, #986, #1006, or AWS migration work.

If any requirement cannot be met within this boundary, stop and report the specific blocker. Do not broaden the task independently.

**Comment by liyang6620** [comment]
## Mandatory execution specification for the delegated #928 work

This comment is an operational addendum to the backend-owner delegation above. Treat every **MUST**, **MUST NOT**, and **STOP** below as binding. Do not infer additional permission from the general goal of “completing Step 4.”

The objective is one narrow vertical slice:

`existing claimant.review_agreement -> explicit versioned acceptance -> existing claimant.create_claim -> existing /creation behavior`

Nothing else is in scope.

### Gate 0: do not start from the current shared backend baseline

PR #1021 / Issue #1006 is still open at `0c515aa1da84c8d349ad6f16d419d4d37df26543`; its `backend-quality` check is still pending and it changes shared repository, Claim, Message, Runtime/Handoff, API, and persistence files.

You MUST NOT:

- start #928 backend work from `main@2d6499a7...` and later merge/rebase over #1021 by assumption;
- copy code from #1021 before it is merged;
- edit the #1021 branch;
- resolve a #1021/#928 semantic conflict yourself;
- modify a #1006 test to make #928 pass.

You MAY prepare a read-only implementation map or frontend-only visual structure that does not invent agreement content or submission authority. Shared backend implementation starts only from the latest `origin/main` after #1021 is resolved and its contract is present on main. At that time, fetch again and record the exact new base SHA in the #928 PR.

### Gate 1: approved agreement input is required

Before formal submission can be enabled, the durable #928 record MUST contain all of the following:

- approved agreement/declaration source or approving authority;
- exact display copy, without AI rewriting;
- stable agreement identifier;
- version;
- exact confirmation keys;
- claimant-visible label for each confirmation;
- which confirmations are required;
- the rule for when acceptance becomes stale.

Until all of those inputs exist, STOP at the blocker. Do not create provisional production values, “temporary” legal text, a default declaration, hidden fallback copy, or a test fixture that becomes runtime content.

Prototype content in `GuidedMotorClaim.jsx`, including `guided-motor-prototype-v1`, is explicitly forbidden as a source.

### Maximum authorised backend contract

The backend addition is limited to these four concepts:

1. **One agreement definition**
   - stable `agreement_id`;
   - stable `version`;
   - approved exact claimant-visible copy;
   - bounded required confirmation definitions.

2. **One Claim-scoped acceptance record**
   - authenticated `customer_id`;
   - `claim_id`;
   - agreement ID/version;
   - exact required confirmation results;
   - Claim revision accepted against;
   - acceptance timestamp;
   - stable operation/idempotency identity;
   - only the audit/provenance fields already required by repository conventions.

3. **One acceptance mutation**
   - claimant authenticated and Claim-owned;
   - requires `If-Match` and `Idempotency-Key` using existing conventions;
   - validates the submitted ID/version and all required confirmations server-side;
   - persists acceptance, Claim revision/action projection, idempotency, audit, and realtime atomically using the existing Claim transaction pattern;
   - exact replay returns the same result;
   - changed input under the same key returns the existing idempotency-conflict semantics.

4. **One additional precondition in the existing creation path**
   - current backend Step 3 projection is valid;
   - current agreement acceptance exists and matches the approved current ID/version;
   - acceptance is valid for the current Claim revision according to the published #928 rule;
   - failure occurs before the existing #987 provider operation is invoked.

Do not add a fifth concept. In particular, do not add agreement catalogues, multiple agreement types, jurisdiction selection, policy administration, staff approval, revocation workflows, expiry schedulers, background jobs, migration engines, provider callbacks, or generic document-signing abstractions.

### Required action projection

The authoritative action sequence MUST remain:

1. Before valid acceptance: `claimant.review_agreement` is the only Step 4 primary action; `claimant.create_claim` is unavailable.
2. After valid acceptance: backend projects `claimant.create_claim` for that Claim/revision.
3. If the Claim changes, the agreement version changes, or Step 3 becomes invalid: backend returns to the appropriate earlier safe action and creation is unavailable.
4. After successful creation: preserve the existing terminal/success projection from the current Claim creation contract.

The frontend MUST NOT calculate this sequence from checkbox state, HTTP success alone, or local route state.

### Required submission sequence

The single visible **Submit claim** interaction may orchestrate the bounded acceptance mutation followed by the existing `/api/v1/claims/{claim_id}/creation` call, but:

- it MUST use separate stable idempotency keys for the two distinct server operations;
- retry MUST replay each operation rather than create duplicate acceptance/provider work;
- an acceptance success followed by a creation failure MUST remain recoverable by retrying creation; it MUST NOT create a second acceptance or discard Claim data;
- the frontend MUST reload/use the authoritative revision returned by acceptance before calling `/creation`;
- UI loading state is not backend authority;
- disabling a button is not duplicate protection;
- do not send the agreement text itself back as claimant-authored free text;
- do not modify the existing `/creation` success payload unless a field is strictly required by an explicit #928 acceptance criterion and cannot be read from the existing Claim projection.

### Step 3 validity rule

Reuse #1004 exactly. Do not invent a second payout/contact validity function with different semantics.

At the #928 server boundary, current Step 3 validity means the existing authoritative checks still succeed for:

- owned and active Payment Destination;
- confirmed registered `claimant.contact_preference`;
- current claimant/contact authority revision;
- active account and usable selected contact destination.

Do not hold the SQLite identity transaction/guard over the external provider call. Do not change the #1004 guard implementation. Do not change profile update semantics. If the current contracts cannot provide a bounded pre-provider Step 3 check without modifying #1004 or #987 internals, STOP and report the exact conflict.

### Preserve #987 without alteration

The existing creation boundary owns all of the following and MUST remain authoritative:

- complete Evidence snapshot/provenance validation;
- authorised route/source validation;
- durable pre-provider operation identity/reservation;
- one provider invocation winner;
- exact replay;
- delivery/failure classification;
- `unknown_outcome` handling;
- reconciliation;
- atomic settlement and terminal Claim projection.

#928 may add preconditions before this boundary. It MUST NOT rewrite, fork, inline, bypass, or generalise this machinery. Do not create a second Claim-creation operation record. Do not compensate or roll back an external provider result because agreement validation was performed too late; agreement validation must be complete before entering the provider boundary.

### Explicit forbidden changes

MUST NOT modify or reinterpret:

- Message creation, Message ordering, reply graphs, actor/visibility rules, or replay aliases;
- Evidence validation, Evidence ordering, or Evidence provenance vocabulary;
- anonymous Claim promotion;
- Runtime or Handoff result persistence/replay;
- ExternalTask attempt, outcome, retry, or reconciliation;
- Workbench permissions, staff roles, queue/detail/actions, or least privilege;
- Agent prompts, model behavior, tool registry, or Runtime policy;
- PaymentDestination storage/masking;
- Profile update behavior or email/phone normalization;
- AWS, DynamoDB, S3, Cognito, IaC, deployment, or provider configuration;
- CI workflows, dependency files, repository automation, Kanban, assignees, or PR readiness;
- unrelated frontend routes/components.

Do not fix adjacent defects. Do not rename shared concepts. Do not move files for cleanliness. Do not introduce base classes/frameworks for a single agreement flow. Do not reformat untouched blocks. Do not add compatibility behavior for hypothetical future agreements.

### Allowed implementation surface

The final PR MAY change only the minimum files belonging to these categories:

- one narrowly named agreement domain module, if no existing model is suitable;
- claimant-safe Claim/action projection;
- the claimant Claim API route needed for the acceptance mutation;
- Claim-creation service only for the new precondition call;
- persistence protocol plus Fixture/Mongo implementations only for the acceptance record and atomic acceptance mutation;
- claimant Step 4 component/API client;
- focused #928 backend/frontend tests;
- `docs/api.md`, `docs/persistence-schema.md`, OpenAPI snapshot, and one narrowly scoped current contract document only when required by actual contract changes.

Before the first commit, list the proposed changed files in the PR description. If implementation requires a file outside these categories, STOP and explain the exact invariant that cannot otherwise be satisfied. “Existing code is there,” “refactoring is cleaner,” or “the AI recommends it” is not sufficient.

### Required failure behavior

All of these MUST fail before provider invocation and MUST leave no false acceptance/creation success:

- missing agreement acceptance;
- wrong agreement ID/version;
- any required confirmation missing or false;
- stale Claim revision;
- acceptance bound to a different claimant or Claim;
- acceptance stale under the published revision rule;
- Step 3 currently incomplete or invalid;
- unavailable/inactive payout destination;
- unusable or stale contact authority;
- reused idempotency key with a different payload.

Use the repository's existing error envelope and closest established status/code semantics. Do not invent multiple new error codes when one bounded agreement-invalid/stale code plus existing revision/idempotency codes is sufficient. Document every new public code.

### Exact minimum tests

The PR MUST contain focused tests proving distinct behavior, not dozens of near-duplicates:

Backend/API:

1. agreement definition projection is claimant-safe and exact;
2. valid acceptance persists once with revision, idempotency, audit, and realtime;
3. one parameterized validation test covers missing/false required confirmations and wrong/stale version;
4. foreign claimant/Claim acceptance is rejected;
5. exact acceptance replay is stable and changed-key payload conflict is rejected;
6. creation without acceptance is rejected before adapter invocation;
7. creation with stale acceptance is rejected before adapter invocation;
8. creation with invalidated Step 3 is rejected before adapter invocation;
9. valid acceptance plus creation invokes the existing adapter exactly once;
10. same-key creation replay does not invoke the adapter again;
11. existing #987 unknown-outcome/reconciliation behavior remains unchanged;
12. Fixture and Mongo parity cover acceptance storage and atomic mutation.

Frontend:

13. exact backend agreement copy and required confirmations render without local legal text;
14. Submit is unavailable until required confirmations are selected;
15. the visible submit flow sends acceptance, consumes its returned revision, then calls creation once;
16. retry after creation failure does not lose Claim state or create another acceptance;
17. success shows only the existing returned Claim/reference data;
18. switching Claims clears local confirmation/error state;
19. staff-only/internal fields are never rendered.

Do not duplicate all existing #987 recovery tests. Run them impact-scoped and add only the #928 regression needed to prove preservation.

### Required work order

Follow this order exactly:

1. Wait for Gate 0 and Gate 1.
2. Fetch latest `origin/main`; record its SHA.
3. Re-read #928, the merged #1004 contract, `docs/claim-creation-boundary.md`, current `/creation` code/tests, and merged #1021 changes.
4. Write the exact proposed request/response/persistence/action contract in the PR description before broad implementation.
5. Implement the smallest backend contract and focused tests.
6. Implement the frontend only against that backend contract.
7. Fetch latest main again and inspect every overlapping shared file.
8. Run focused and impact-selected validation, then push without force-pushing over teammate work.
9. Wait for exact-head CircleCI and fix all failures.
10. Request review with the full evidence required by the delegation comment.

### STOP conditions

Stop immediately and report before continuing if:

- approved copy/source/confirmation semantics are missing;
- #1021 is not yet merged but shared backend editing would overlap it;
- a semantic conflict exists with #1004, #987, or #1006;
- a change to Message/Evidence/Runtime/Handoff/ExternalTask/Workbench/AWS behavior appears necessary;
- the solution requires a second creation lifecycle, generic agreement platform, background worker, or provider change;
- the existing creation success contract must be broken;
- Fixture and Mongo cannot implement the same authoritative behavior;
- tests can pass only by weakening an existing invariant;
- current main changes after local validation in an overlapping contract area.

At a STOP condition, provide the file, exact SHAs, conflicting contracts, and smallest proposed resolution. Do not let an AI choose a broader solution.

### Definition of done

#928 is not done merely because a page renders or a mocked create call returns 201. It is review-ready only when approved copy is traceable, acceptance is durable and auditable, backend action projection owns progression, direct API bypass is blocked, #987 behavior is preserved, Fixture/Mongo parity passes, frontend failure/retry state is covered, exact-head CI is green, and the complete Issue acceptance criteria are mapped to evidence.

Any implementation outside this specification is unauthorised, even if its tests pass.

**Comment by Ysoseri1224** [comment]
## Maintainer decision: Gate 1 satisfied

Proceed with the Step 4 agreement contract exactly as proposed and bounded above. I approve it as the authoritative contract for Issue #928 and the current VP implementation. Do not invent, paraphrase, or add any other agreement content.

This approval is limited to the Step 4 agreement, explicit acceptance, action projection, creation precondition, claimant UI, persistence, and focused contract evidence already defined in this Issue.

**Do not modify Agent behavior or Agent logic.** In particular, do not modify Runtime orchestration or policy, Agent prompts, model behavior, `backend/services/messages.py`, or related turn reducer/router/message-processing behavior. If implementation appears to require any such change, stop before editing and @Ysoseri1224 here with the exact file, reason, intended behavior change, and impact for further evaluation.

With this maintainer decision recorded, Gate 1 is satisfied and implementation may proceed within the approved #928 boundary.
